(* ::Package:: *)

(* ::Input:: *)
(*(* :Title:InstrumentQuiz*)*)
(*(* :Context:InstrumentQuiz`*)*)
(*(* :Author:VT*)*)
(*(* :Summary:instrument quiz package*)*)
(*(* :Copyright:*)*)
(*(* :Package Version:1,Maggio 2020*)*)
(*(* :Mathematica Version:11.2*)*)
(*(* :History:*)*)
(*(* :Sources:*)*)
(*(* :Limitations:*)(* :Discussion:*)*)


(* ::Input:: *)
(*BeginPackage["InstrumentQuiz`"];*)
(**)
(*pathImg = StringReplace[NotebookDirectory[],"package\\" -> ""];*)
(*SetDirectory[pathImg];*)
(*MakeInstrumentQuiz::usage="MakeInstrumentQuiz []*)
(*Create some random exercise  with instrument, check name, type and sound of an instrument."*)
(**)
(*$instrumentList::usage="$instrumentList*)
(*Is the global luist of instrument."*)
(**)
(*$instrumentList = { *)
(*{"Batteria","Percussione"},*)
(*{"Clarinetto","Fiato"},*)
(*{"Piano","Tastiera"},*)
(*{"Pianola","Tastiera"},*)
(*{"Sassofono soprano","Fiato"},*)
(*{"Tamburo","Percussione"},*)
(*{"Viola","Corda"} ,*)
(*{"Violino","Corda"},*)
(*{"Violoncello","Corda"}*)
(*};*)
(**)
(**)
(*quizList = {*)
(*{"L'archetto \[EGrave] una bacchetta di legno con dei fili di metallo tesi.",*)
(*"F",*)
(*"Falso. Si tratta di una bacchetta di legno con dei crini di cavallo tesi."*)
(*},*)
(**)
(*{"L'archetto \[EGrave] un accessorio che serve per suonare strumenti dotati di corde come il violino.",*)
(*"V",*)
(*"Vero. Serve per suonare anche la viola, il violoncello e il contrabbasso."*)
(*},*)
(**)
(*{"L'ancia \[EGrave] una linguetta mobile che produce il suono di alcuni strumenti a fiato.",*)
(*"V",*)
(*"Vero. Il suono viene prodotto dalla vibrazione dell'ancia causata dall'ingresso dell'aria."*)
(*},*)
(**)
(*{"L'Oboe \[EGrave] uno strumento ad ancia semplice.",*)
(*"F",*)
(*"Falso. L'Oboe \[EGrave] uno strumento ad ancia doppia."*)
(*},*)
(**)
(*{"Il clarinetto \[EGrave] uno strumento della famiglia degi ottoni.",*)
(*"F",*)
(*"Falso. Il clarinetto appartiene alla famiglia dei legni."*)
(*},*)
(*{*)
(*"Il pianoforte \[EGrave] uno strumento a corde percosse.",*)
(*"V",*)
(*"Vero. Le corde vengono percosse da dei martelletti azionati dalla tastiera."*)
(*},*)
(**)
(*{"Il liuto \[EGrave] uno strumento a corde pizzicate.",*)
(*"V",*)
(*"Vero. Il liuto \[EGrave] uno strumento europeo del barocco/rinascimento che viene suonato tramite il pizzico delle corde."*)
(*},*)
(*{"Lo xilofono \[EGrave] uno strumento membranofono.",*)
(*"F",*)
(*"Falso. Lo xilofono \[EGrave] uno strumento idiofono cio\[EGrave] privo di membrana."*)
(*},*)
(*{"Il timpano \[EGrave] uno strumento membranofono.",*)
(*"V",*)
(*"Vero, Il timpano \[EGrave] considerato il re dei membranofoni."*)
(*}*)
(**)
(*};*)
(**)
(**)
(*For[i = 1, i <= Length[$instrumentList],i++,*)
(*sub = $instrumentList[[i]];*)
(*pic = Import["immagini/strumenti/"<>sub[[1]]<>".jpg"];*)
(*$instrumentList[[i]] = Append[$instrumentList[[i]],pic];*)
(*]*)


(* ::Input:: *)
(*Begin["`Private`"];*)
(**)
(*MakeInstrumentQuiz[] := Module[*)
(*{random = 0,ret = Null},*)
(*SeedRandom[];*)
(*random = RandomInteger[{1,300}];*)
(*If[random <= 100,*)
(**)
(*ret  = MakeNameQuiz[];(*Print["1",ret];*),*)
(*If[random > 100 && random <= 200,*)
(*	ret  = MakeTypeQuiz[];(*Print["2",ret];*),*)
(*(*ret  = MakeSoundQuiz[]*)*)
(*ret = MakeTFQuiz[];(* Print["3",ret]*);*)
(*]*)
(*];*)
(*Return[ret];*)
(*]*)
(**)
(*MakeTFQuiz[] := Module[*)
(*{random = 0,sub = Null,list = quizList},*)
(*SeedRandom[];*)
(*random = RandomInteger[{1,Length[list]}];*)
(*sub = list[[random]];*)
(*question =  sub[[1]];*)
(*answer = sub[[2]];*)
(*explain = sub[[3]];*)
(*userAnswer = Null;*)
(*panel = Panel[*)
(*	Column[{*)
(*Row[{Style[question,FontFamily->"Arial-Bold",16]}],*)
(*Spacer[225 0.7],*)
(*Row[{RadioButtonBar[Dynamic[userAnswer],{"V"->"Vero","F"->"Falso"}] }],*)
(*Row[{ makeButtonControlCol[answer,explain,userAnswer]}]*)
(**)
(*	}]*)
(*	,ImageSize->700];*)
(*(*buttonPanel = makeButtonControl[answer,explain];*)
(*panelTot = Panel[*)
(*Column[{panel,*)
(*buttonPanel*)
(*}]*)
(*];*)*)
(*panelTot = panel;*)
(**)
(*Return[panelTot];*)
(**)
(*]*)
(**)
(*MakeNameQuiz[] := Module[*)
(*{ list = $instrumentList,random = 0, sub = Null},*)
(**)
(*SeedRandom[];*)
(*random = RandomInteger[{1,Length[list]}];*)
(*(*Random choice of a instrument*)*)
(*sub = list[[random]];*)
(*list = Delete[list,random];*)
(*picture = sub[[3]];*)
(*name = sub[[1]];*)
(*userAnswer = Null;*)
(*toChoose = {}; (*Random list of instrument name*)*)
(*For[answer = 1, answer <= 3,answer++,*)
(*	SeedRandom[];*)
(*	random = RandomInteger[{1,Length[list]}];*)
(*  elem =list[[random]];*)
(*  toChoose = Append[toChoose,elem[[1]]];*)
(*list = Delete[list,random];*)
(*];*)
(*newPos = RandomInteger[{1,3}];*)
(*toChoose = Insert[toChoose,name,newPos];*)
(*panel = Panel[*)
(*Row[{*)
(*Column[{*)
(*Magnify[Dynamic[picture],4.5]*)
(*}],*)
(*Spacer[225 0.7],*)
(*Column[{*)
(*Row[{Dynamic[RadioButtonBar[Dynamic[userAnswer],toChoose,Appearance->"Vertical"]]}],*)
(*Row[{ makeButtonControlCol[name,"",userAnswer]}]*)
(*}],*)
(*Spacer[15 0.7]*)
(*}]*)
(*,ImageSize->700];*)
(**)
(*(*buttonPanel = makeButtonControl[answer,""];*)
(*panelTot = Panel[*)
(*Column[{panel,*)
(*buttonPanel*)
(*}]*)
(*];*)*)
(*panelTot = panel;*)
(**)
(*Return[panelTot];*)
(**)
(*]*)
(**)
(**)
(*MakeTypeQuiz[] := Module[*)
(*{ list = $instrumentList,random = 0, sub = Null},*)
(*toChoose = {"Fiato","Percussione","Tastiera","Corda"};*)
(*SeedRandom[];*)
(*random = RandomInteger[{1,Length[list]}];*)
(*(*Random choice of a instrument*)*)
(*sub = list[[random]];*)
(*picture = sub[[3]];*)
(*name = sub[[2]];*)
(*userAnswer = Null;*)
(*panel = Panel[*)
(*Row[{*)
(*Column[{*)
(*Magnify[Dynamic[picture],4.5]*)
(*}],*)
(*Spacer[225 0.7],*)
(*Column[{*)
(*Row[{Dynamic[RadioButtonBar[Dynamic[userAnswer],toChoose,Appearance->"Vertical"]]}],*)
(*Row[{ makeButtonControlCol[name,"",userAnswer]}]*)
(*}],*)
(*Spacer[15 0.7]*)
(*}]*)
(*,ImageSize->700];*)
(*(*buttonPanel = makeButtonControl[answer,""];*)
(*panelTot = Panel[*)
(*Column[{panel,*)
(*buttonPanel*)
(*}]*)
(*];*)*)
(*panelTot = panel;*)
(**)
(*Return[panelTot];*)
(**)
(*]*)
(**)
(**)
(**)
(*Attributes[makeButtonControlCol]={HoldAll};*)
(*makeButtonControlCol[answer_,explain_,userAnswer_]:=Module[*)
(*{},*)
(*answered = False;*)
(*row = Row[{*)
(*Button["Submit",*)
(*			If[userAnswer == answer,*)
(*				answered = True; MessageDialog["Esatto! " <> explain],*)
(*				answered = True; MessageDialog["Sbagliato! " <> explain],*)
(*	    MessageDialog["Seleziona una risposta!"]*)
(*			]*)
(*		],*)
(*Button["Next",*)
(*If[answered == True,*)
(*MakeInstrumentQuiz[],*)
(*MessageDialog["Devi prima rispondere alla domanda!"],*)
(*MessageDialog["Devi prima rispondere alla domanda!"]*)
(*]*)
(*	]*)
(*}];*)
(*Return[row];*)
(*]*)
(**)
(**)
(**)
(*End[]*)
(*EndPackage[]*)


 
