(* ::Package:: *)

(* ::Input:: *)
(*(* :Title:MusicUtilities*)*)
(*(* :Context:MusicUtilities`*)*)
(*(* :Author:GS*)*)
(*(* :Summary:music lesson utilities*)*)
(*(* :Copyright:*)*)
(*(* :Package Version:1,Maggio 2020*)*)
(*(* :Mathematica Version:11.2*)*)
(*(* :History:*)*)
(*(* :Sources:*)*)
(*(* :Limitations:*)(* :Discussion:*)*)


(* ::Input:: *)
(*BeginPackage["MusicUtilities`"];*)
(*Begin["`Private`"];*)
(**)
(*$notesUS = {"C","D","E","F","G","A","B","C4","D4","E4","F4","G4","A4","B4","C6","D6","E6","F6","G6","A6","B6"};*)
(*$notesEU = {"Do","Re","Mi","Fa","Sol","La","Si","Do4","Re4","Mi4","Fa4","Sol4","La4","Si4","Do6","Re6","Mi6","Fa6","Sol6","La6","Si6"};*)
(**)
(**)
(**)
(*listOfList::usage="listOfList [list]*)
(*Check if a list have another list inside."*)


(* ::Input:: *)
(*toLabelList::usage="toLabelList [toConv,toApp,type]*)
(*Convert the list of musical notes (toConv) into the sistem specified by type ('u' : us, 'e': eu)."*)
(**)
(*listOfList[toCheck_] := Module[*)
(*{i = 1,toRet = False},*)
(*lenList = Length[toCheck];*)
(*For[i=1,i<  lenList+1,i++,*)
(*If[Length[toCheck[[i]]] != 0,*)
(*toRet = True; i = lenList;*)
(*]*)
(*] ;*)
(*Return[toRet];                     *)
(*]*)
(**)
(**)
(**)
(**)
(*toLabelList[{}]:= Module[{},Return["--"]]; *)
(*toLabelList[toConv_  /; listOfList[toConv] == False, toApp_,type_]:=Module[*)
(*{notesStart = {},notesEnd = {}, i = 1,toConvert = toConv, toAppend = toApp},*)
(*If[type == "u",*)
(*notesStart =$notesEU;*)
(*notesEnd = $notesUS,*)
(*notesStart =$notesUS;*)
(*notesEnd = $notesEU;*)
(*];*)
(*(*toConvert = removeNumber[toConvert];*)*)
(*lenList = Length[toConvert] + 1;*)
(*temp = toAppend;*)
(*For[i=1,i<  lenList,i++,*)
(**)
(*index =FirstPosition[notesStart,toConvert[[i]]];*)
(*newElem = Part[notesEnd[[index]],1];*)
(*temp = Append[temp, newElem];*)
(**)
(* ];*)
(*Return[temp];*)
(*]*)
(**)
(*toLabelList[toConv_/; listOfList[toConv] == True,toApp_,type_]:=Module[*)
(*{notesStart = {},notesEnd = {}, i = 1,toConvert = toConv, toAppend = toApp, lenList = Length[toConv] +1},*)
(*If[type == "u",*)
(*notesStart =$notesEU;*)
(*notesEnd = $notesUS,*)
(**)
(*notesStart =$notesUS;*)
(*notesEnd = $notesEU*)
(*];*)
(*(*toConvert = removeNumber[toConvert];*)*)
(*temp = toAppend;*)
(*For[i=1,i <  lenList,i++, *)
(*If[*)
(*Length[toConvert[[i]]] == 0,*)
(**)
(*index =FirstPosition[notesStart,toConvert[[i]]]; (*then*)*)
(*newElem = Part[notesEnd[[index]],1];*)
(*temp = Append[temp, newElem];  ,*)
(**)
(*newTemp = {};*)
(*newList = toConvert[[i]];*)
(*temp = Append[temp,toLabelList[newList,newTemp ,type]] ;(*else*)*)
(*];*)
(*];*)
(*Return[temp]*)
(*]*)
(**)
(**)
(*removeNumber[toConvert_] := Module[*)
(*{i =1},*)
(*temp = {};*)
(*lenList = Length[toConvert] +1;*)
(*For[i=1,i <  lenList,i++, *)
(*temp = Append[Replace[toConvert[[i]], RegularExpression["[0-9]+"] -> "" ]];*)
(*];*)
(*Print["TEEEMP ",temp];*)
(*Return[temp]*)
(*]*)
(**)
(**)
(**)


(* ::Input:: *)
(*End[]*)
(*EndPackage[]*)
